apiVersion: batch/v1
kind: Job
metadata:
  name: delete-runtime-applications
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccount: argocd-application-controller
      restartPolicy: Never
      containers:
      - name: delete-runtime-resources
        image: "{{ .Values.runtimeInstallation.image.repository }}:{{ .Values.runtimeInstallation.image.tag | default .Chart.Version }}"
        imagePullPolicy: {{ .Values.runtimeInstallation.image.pullPolicy }}
        command: ["sh", "-c"]
        args: ["kubectl delete applicationset -l codefresh.io/internal=true --cascade=foreground"]