apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: codefresh-runtime-install-params1
    behavior: create
    options:
      annotations: 
        argocd.argoproj.io/hook: Skip # Tell argocd to skip this - the actual values are set from helm
    literals:
      - ingressHost=PLACEHOLDER
      - ingressClass=PLACEHOLDER

replacements:
  # template the version from the configmap into the applicationset generators
  - source:
      kind: ConfigMap
      name: codefresh-runtime-install-params
      fieldPath: data.ingressHost
    targets:
      - select:
          kind: Ingress
          name: cap-app-proxy
        fieldPaths:
          - spec.rules.0.host
  - source:
      kind: ConfigMap
      name: codefresh-runtime-install-params
      fieldPath: data.ingressClass
    targets:
      - select:
          kind: Ingress
          name: cap-app-proxy
        fieldPaths:
          - spec.ingressClassName
